server:
  port: 8081


spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fund_db?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      #????????? 10
      maximum-pool-size: 30
      #???????
      minimum-idle: 10
      #??????????30000 (??)
      connection-timeout: 60000
      #??????????????
      idle-timeout: 60000
      #????????????? 0 ????????????
      max-lifetime: 600000
      #?????????????(?)
      login-timeout: 5

#mybatis-plus配置
mybatis-plus:
  # Mapper扫描位置
  mapper-locations: classpath*:com/fund/**/mapper/*.xml
  # 实体类扫描位置
  type-aliases-package: com.fund.infras.dao.model
  configuration:
    cache-enabled: true
    #    开启控制台打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #    开启驼峰命名
    map-underscore-to-camel-case: true
  #  全局配置逻辑删除
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

logging:
  config: classpath:log4j2-spring.xml
  level:
    #这个指定你的dao层，也就是mapper文件的所在包
    com.fund.infras.dao.mapper: debug
#定时任务xxl-job
xxl:
  job:
    enable: true
    admin:
      addresses: http://localhost:8080/xxl-job-admin
    accessToken: default_token
    executor:
      appname: lkm-job
      address:
      ip:
      port: 9996
#      # 日志地址
      logpath: /data/applogs/xxl-job/jobhandler
#      # 日志保存时间
      logretentiondays: 30
